# Generated by Django 5.0.7 on 2024-08-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12)),
                ("effect", models.CharField(max_length=511)),
                ("pp", models.IntegerField()),
                ("power", models.IntegerField()),
                ("accuracy", models.IntegerField()),
                ("move_type", models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                ("speciesId", models.IntegerField()),
                ("pokedexId", models.IntegerField()),
                ("type1", models.CharField(max_length=127)),
                ("type2", models.CharField(max_length=127)),
                ("hp", models.IntegerField()),
                ("attack", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("speed", models.IntegerField()),
                ("special_attack", models.IntegerField()),
                ("special_defense", models.IntegerField()),
            ],
        ),
    ]
