# Generated by Django 5.0.7 on 2024-08-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="move",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
