# Generated by Django 5.0.7 on 2024-08-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_id_item_item_id_rename_id_move_move_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="move_pool",
            field=models.ManyToManyField(to="core.move"),
        ),
    ]
