# Generated by Django 5.0.7 on 2024-08-14 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_species_move_pool"),
    ]

    operations = [
        migrations.RenameField(
            model_name="species",
            old_name="pokedexId",
            new_name="pokedex_id",
        ),
        migrations.RenameField(
            model_name="species",
            old_name="speciesId",
            new_name="species_id",
        ),
    ]
