# Generated by Django 5.0.7 on 2024-08-14 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_pokedexid_species_pokedex_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="species",
            name="move_pool",
        ),
        migrations.DeleteModel(
            name="Move",
        ),
    ]
