# Generated by Django 5.0.7 on 2024-08-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_move"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="move_pool",
            field=models.ManyToManyField(to="core.move"),
        ),
    ]
