# Generated by Django 5.0.7 on 2024-08-31 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_move_id_move_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='growth_rate',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='core.species')),
            ],
            options={
                'verbose_name': 'Ability',
                'verbose_name_plural': 'Abilities',
            },
        ),
    ]
