const NATURES = [
  { name: "Hardy", increase: 'Atk', decrease: 'Atk' },
  { name: "Lonely", increase: 'Atk', decrease: 'Def' },
  { name: "Brave", increase: 'Atk', decrease: 'Spe' },
  { name: "Adamant", increase: 'Atk', decrease: 'SpA' },
  { name: "Naughty", increase: 'Atk', decrease: 'SpD' },
  { name: "Bold", increase: 'Def', decrease: 'Atk' },
  { name: "Docile", increase: 'Def', decrease: 'Def' },
  { name: "Relaxed", increase: 'Def', decrease: 'Spe' },
  { name: "Impish", increase: 'Def', decrease: 'SpA' },
  { name: "Lax", increase: 'Def', decrease: 'SpD' },
  { name: "Timid", increase: 'Spe', decrease: 'Atk' },
  { name: "Hasty", increase: 'Spe', decrease: 'Def' },
  { name: "Serious", increase: 'Spe', decrease: 'Spe' },
  { name: "Jolly", increase: 'Spe', decrease: 'SpA' },
  { name: "Naive", increase: '', decrease: '' },
  { name: "Modest", increase: 'SpA', decrease: 'Atk' },
  { name: "Mild", increase: 'SpA', decrease: 'Def' },
  { name: "Quiet", increase: 'SpA', decrease: 'Spe' },
  { name: "Bashful", increase: 'SpA', decrease: 'SpA' },
  { name: "Rash", increase: 'SpA', decrease: 'SpD' },
  { name: "Calm", increase: 'SpD', decrease: 'Atk' },
  { name: "Gentle", increase: 'SpD', decrease: 'Def' },
  { name: "Sassy", increase: 'SpD', decrease: 'Spe' },
  { name: "Careful", increase: 'SpD', decrease: 'SpA' },
  { name: "Quirky", increase: 'SpD', decrease: 'SpD' },
];

export default NATURES;
